version: '3'

services:

  mysql:
    image: mysql:5.7
    ports:
      - '3006:3306'
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secretPasswordToBeSetInAnotherPlaceInTheFuture
      - MYSQL_USER=desafio
      - MYSQL_PASSWORD=mudar123
      - MYSQL_DATABASE=b2wadds

  rabbitmq:
    image: rabbitmq:3.7
    ports:
      - '5672:5672'
    volumes:
      - ./docker_volumes/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretPhrase
      - RABBITMQ_DEFAULT_USER=desafio
      - RABBITMQ_DEFAULT_PASS=mudar123

  foo:
    build:
      context: .
      dockerfile: ./foo/Dockerfile
    ports:
      - '3002:3000'

  fighters:
    build:
      context: .
      dockerfile: ./fighters/Dockerfile
    ports:
      - '3003:4000'

  desafio:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mysql
      - rabbitmq
      - foo
      - fighters
    links:
      - mysql
      - rabbitmq
      - foo
      - fighters
    environment:
      - DB_USER=desafio
      - DB_PASS=mudar123
      - DB_HOST=mysql
      - DB_PORT=3006
      - DB_NAME=b2wadds
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=fila1
      - RABBITMQ_USER=desafio
      - RABBITMQ_PASS=mudar123
      - TICKET_CONTROL_HOST=foo
      - TICKET_CONTROL_PORT=3002
      - VALUE_CONTROL_HOST=fighters
      - VALUE_CONTROL_PORT=3003

volumes:
  mysql:
  desafio:
