version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - '3006:3306'
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretPasswordToBeSetInAnotherPlaceInTheFuture
      - MYSQL_USER=desafio
      - MYSQL_PASSWORD=mudar123
      - MYSQL_DATABASE=b2wadds
  desafio:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_USER=desafio
      - DB_PASS=mudar123
      - DB_HOST=mysql
      - DB_PORT=3006
      - DB_NAME=b2wadds
  foo:
    build:
      context: .
      dockerfile: ./foo/Dockerfile
    ports:
      - '3002:3000'
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_USER=desafio
      - DB_PASS=mudar123
      - DB_HOST=mysql
      - DB_PORT=3006
      - DB_NAME=b2wadds
  fighters:
    build:
      context: .
      dockerfile: ./fighters/Dockerfile
    ports:
      - '3003:4000'
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_USER=desafio
      - DB_PASS=mudar123
      - DB_HOST=mysql
      - DB_PORT=3006
      - DB_NAME=b2wadds

volumes:
  mysql:
  desafio:
